name: Build Android APK (unzip + generate wrapper if placeholder + build)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo root (diagnostic)
        run: |
          echo '---- repo root listing ----'
          ls -la
          echo '---- end repo root listing ----'
        shell: bash

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install common packages (wget/unzip/gradle/rsync)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y wget unzip git ca-certificates apt-transport-https gnupg rsync
          # install a system gradle so we can generate a wrapper if needed
          sudo apt-get install -y gradle
        shell: bash

      - name: Install Android commandline tools and SDK packages
        run: |
          # use runner temp for SDK
          ANDROID_SDK_ROOT="$RUNNER_TEMP/android-sdk"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/"* "$ANDROID_SDK_ROOT/cmdline-tools/latest/" || true
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-33" "build-tools;33.0.2" || true
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        shell: bash

      - name: If there's a zip, list and unzip to extracted/ then merge into repo root
        run: |
          set -euo pipefail
          mkdir -p extracted
          # enable nullglob so that the *.zip expands to empty array when no matches
          shopt -s nullglob || true
          zips=( *.zip )
          if [ "${#zips[@]}" -gt 0 ]; then
            echo "ZIP files found: ${zips[*]}"
            for z in "${zips[@]}"; do
              echo "Unzipping $z -> extracted/"
              unzip -o "$z" -d extracted
            done
            echo "Merging extracted contents into repo root (preserving .git)"
            # copy extracted content into repo root, overwrite files but keep .git
            rsync -a --exclude '.git' extracted/ ./
            ls -la
          else
            echo "No zip files found in repo root."
          fi
        shell: bash

      - name: Ensure Gradle wrapper exists (generate if placeholder or missing)
        run: |
          set -euo pipefail
          # If gradlew is missing or the placeholder message is present, generate the wrapper using system gradle
          if [ ! -f ./gradlew ] || grep -q "placeholder gradlew" ./gradlew 2>/dev/null || grep -q "placeholder gradlew" ./gradlew.bat 2>/dev/null; then
            echo "Gradle wrapper missing or placeholder detected — generating wrapper with system gradle"
            # system gradle should be installed in earlier step
            gradle wrapper --gradle-version 8.0.2
            chmod +x ./gradlew || true
          else
            echo "Gradle wrapper appears present and not placeholder"
          fi
        shell: bash

      - name: Build APK (assembleDebug)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
        run: |
          set -euo pipefail
          export TERM=dumb
          ./gradlew assembleDebug --no-daemon
        shell: bash
